"""The identity file: a human-readable Markdown view of everything remembered.

It is regenerated from the memories table after every change, so editing or
forgetting a memory in the app is reflected here immediately. The database is
the source of truth.
"""
from __future__ import annotations

from pathlib import Path

from .store import MEMORY_KINDS, Store

HEADINGS = {
    "preference": "Preferences",
    "fact": "Facts",
    "person": "People",
    "place": "Places",
    "routine": "Routines",
}


def render(store: Store, agent_name: str = "the assistant") -> str:
    memories = store.list_memories()
    lines = [
        "# About me",
        "",
        f"_What {agent_name} remembers. Generated by LocalAIAgent; edit or forget items in the app._",
        "",
    ]
    if not memories:
        lines.append("_Nothing remembered yet._")
    for kind in MEMORY_KINDS:
        items = [m for m in memories if m.kind == kind]
        if not items:
            continue
        lines.append(f"## {HEADINGS[kind]}")
        lines += [f"- {m.text}" for m in items]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write(store: Store, path: Path, agent_name: str = "the assistant") -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = render(store, agent_name)
    path.write_text(text, encoding="utf-8")
    return text
